name: tarkhine
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  lottie: ^2.4.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  pin_code_fields: ^7.4.0
  equatable: ^2.0.5
  iconsax: ^0.0.8
  http: ^1.0.0
  shimmer: ^3.0.0
  dots_indicator: ^3.0.0
  connectivity_plus: ^4.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mlogo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/lotties/

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Bold.ttf
        - asset: assets/fonts/Estedad-Black.ttf
        - asset: assets/fonts/Estedad-ExtraBold.ttf
        - asset: assets/fonts/Estedad-ExtraLight.ttf
        - asset: assets/fonts/Estedad-Light.ttf
        - asset: assets/fonts/Estedad-Medium.ttf
        - asset: assets/fonts/Estedad-Regular.ttf
        - asset: assets/fonts/Estedad-SemiBold.ttf
        - asset: assets/fonts/Estedad-Thin.ttf

