# Generated by Django 4.2.4 on 2023-08-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcover',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='api.food'),
        ),
    ]
