# Generated by Django 4.2.4 on 2023-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_foodcover_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('delivered', 'delivered')], default='pending', max_length=10),
        ),
    ]
