# Generated by Django 4.2.4 on 2023-08-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
