# Generated by Django 4.2.4 on 2023-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcover',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
