# Generated by Django 4.2.4 on 2023-09-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_foodcover_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcover',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
