# Generated by Django 4.2.4 on 2023-09-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_foodcover_food_alter_foodcover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
