# Generated by Django 4.2.5 on 2023-09-05 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_food_comments_alter_food_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
