# Generated by Django 4.2.5 on 2023-09-06 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_food_discount_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
