# Generated by Django 4.2.5 on 2023-09-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_liked',
        ),
    ]
